project:
  type: website
  output-dir: _site
  render:
    - "**/*.qmd"
    - "**/*.ipynb"
    - "!templates/**"
website:
  title: "ERG Topic Forum"
  site-url: https://earthquake-research-group.github.io/erg-topic-forum
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sessions/index.qmd
        text: Sessions
      - href: topics/reading-list.qmd
        text: Reading list
      - href: topics/glossary.qmd
        text: Glossary
      - href: docs/how-to.qmd
        text: How to use
  comments:
    giscus:
      repo: earthquake-research-group/erg-topic-forum
      repo-id: R_kgDORThOtQ
      category: General
      category-id: DIC_kwDORThOtc4C21tY
      mapping: pathname

bibliography: bibliography/references.bib

format:
  html:
    theme:
      - cosmo
      - styles/erg-theme.scss
    toc: true
    code-copy: true
    html-math-method:
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
