blank_issues_enabled: true
contact_links:
  - name: ERG Topic Forum website
    url: https://earthquake-research-group.github.io/erg-topic-forum/
    about: Browse existing sessions and instructions.
